### ISSUE TITLE
Add Dynamic Cluster Management with applying existing RBAC.

### ISSUE THREAD

**Issue by husenkuresh1** [Improwised/kube-oidc-proxy#50]
The kube-oidc-proxy currently lacks support for dynamic cluster management

## Proposed Solution
Enable the proxy to dynamically discover, add, update, and remove clusters using kubeconfig data stored in Kubernetes secrets. The name and namespace of the secret will be provided from flags, like ```secret-name``` and ```--secret-namespace```. 

The secret will look like
```
apiVersion: v1
kind: Secret
metadata:
  name: multi-cluster-kubeconfigs
  namespace: default
data:
  cluster1: <kubeconfig data>
  cluster2: <kubeconfig data>
```
here ```cluster1``` and ```cluster2``` is cluster name, the request for cluster through proxy will be like ```https://proxy-host:port/cluster1/api/v1/pods````

Ensure seamless coexistence of static and dynamic clusters.
Ensure all the existing CAPI-RBAC roles and bindings created at the global level (for all clusters) automatically work with any new cluster added using a dynamic way.

## Acceptance Criteria
- Dynamic clusters can be added, updated, and removed without restarting the proxy.
- RBAC rules are applied automatically to both static and dynamic clusters.
- Invalid configurations are handled gracefully without affecting valid clusters.
- Unit and e2e tests validate the functionality and reliability of the feature.
